# SSH密钥分发工具配置示例

# hosts.yaml - 主机列表配置
---
hosts:
  # 直接密码认证
  - host: 192.168.1.10
    port: 22
    username: root
    target_user: deploy  # 要添加密钥的用户
    auth_method: password
    auth_value: "YourPassword"  # 生产环境建议用密钥或环境变量

  # 使用密钥认证
  - host: 192.168.1.11
    username: admin
    target_user: deploy
    auth_method: key
    auth_value: /home/user/.ssh/id_rsa
  
  # 通过跳板机
  - host: 10.0.1.100
    username: root
    target_user: app
    auth_method: key
    auth_value: /home/user/.ssh/id_rsa
    jump_host:
      host: jump.example.com
      port: 22
      username: jumper
      key_file: /home/user/.ssh/jump_key
  
  # Web服务器组
  - host: web-01.example.com
    username: deploy
    target_user: deploy
    auth_method: key
    auth_value: /home/user/.ssh/id_rsa
  
  - host: web-02.example.com
    username: deploy
    target_user: deploy
    auth_method: key
    auth_value: /home/user/.ssh/id_rsa

  # 数据库服务器（更严格的验证）
  - host: db-01.example.com
    username: dba
    target_user: mysql
    auth_method: key
    auth_value: /home/user/.ssh/id_rsa
    verify: true  # 启用验证
